# .circleci/config.yml
version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.9.2-eclipse-temurin-21  # Imagen válida de Maven + JDK
    working_directory: ~/proyectoprogram2
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean package