# .circleci/config.yml
version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.9.1-eclipse-temurin-21  # Imagen Maven + JDK 21 válida
    working_directory: ~/proyectoprogram2
    steps:
      - checkout  # Clona tu repositorio
      - run:
          name: Compile project
          command: mvn clean compile
      - run:
          name: Run tests
          command: mvn test
      - run:
          name: Package project
          command: mvn package

workflows:
  build_and_test:
    jobs:
      - build