version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.8.8-eclipse-temurin-17  # Imagen verificada
    working_directory: ~/proyectoprogram2
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean package