# .circleci/config.yml
version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.9.2-eclipse-temurin-21
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean package

workflows:
  build_workflow:
    jobs:
      - build