version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.9.0-eclipse-temurin-21  # Esta sí existe
    working_directory: ~/proyectoprogram2
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean package